# Generated by Django 6.0 on 2025-12-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0002_alter_user_employee_number_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategicplan',
            name='plan_status',
        ),
        migrations.AlterField(
            model_name='initiative',
            name='priority',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userinitiative',
            name='status',
            field=models.CharField(max_length=2),
        ),
    ]
