# Generated by Django 4.2.27 on 2025-12-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0003_alter_department_options_alter_log_options_and_more'),
        ('CPMS_app', '0003_remove_strategicplan_plan_status_and_more'),
    ]

    operations = [
    ]
