# Generated by Django 4.2.27 on 2025-12-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0006_alter_department_id_alter_initiative_id_alter_kpi_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategicplan',
            options={'verbose_name': 'StrategicPlan', 'verbose_name_plural': 'StrategicPlans'},
        ),
        migrations.AddField(
            model_name='strategicplan',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
