# Generated by Django 6.0 on 2026-01-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0008_alter_strategicplan_options_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='priority',
            field=models.CharField(choices=[('C', 'حرجة'), ('H', 'عالية'), ('M', 'متوسطة'), ('L', 'منخفضة')], default='L', max_length=1),
        ),
    ]
