# Generated by Django 6.0 on 2026-01-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0009_alter_initiative_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinitiative',
            name='status',
            field=models.CharField(choices=[('NS', 'لم يبدأ بعد'), ('IP', 'قيد التنفيذ'), ('D', 'متأخر'), ('C', 'مكتمل')], max_length=2),
        ),
    ]
