# Generated by Django 4.2.27 on 2026-01-12 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0010_note_parent_note_note_read_by_note_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='CPMS_app.initiative'),
        ),
        migrations.AlterField(
            model_name='note',
            name='read_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
