# Generated by Django 4.2.27 on 2026-01-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0011_alter_note_created_at_alter_note_initiative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
