# Generated by Django 4.2.27 on 2026-01-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0012_note_is_starred_alter_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='department',
        ),
        migrations.AddField(
            model_name='note',
            name='strategic_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='CPMS_app.strategicgoal'),
        ),
    ]
