# Generated by Django 4.2.27 on 2026-01-14 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0013_remove_note_department_note_strategic_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
