# Generated by Django 4.2.27 on 2026-01-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0010_alter_userinitiative_status'),
        ('CPMS_app', '0014_alter_note_receiver'),
    ]

    operations = [
    ]
