# Generated by Django 6.0 on 2026-01-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0010_alter_userinitiative_status'),
        ('CPMS_app', '0014_alter_note_receiver'),
    ]

    operations = [
    ]
