# Generated by Django 4.2.27 on 2026-01-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0015_merge_20260121_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategicplan',
            options={'ordering': ['-start_date'], 'verbose_name': 'StrategicPlan', 'verbose_name_plural': 'StrategicPlans'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_status',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='note',
            name='last_activity_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
