# Generated by Django 6.0 on 2026-01-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0016_alter_strategicplan_options_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='start_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
