# Generated by Django 4.2.27 on 2026-01-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0016_alter_strategicplan_options_remove_note_note_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
