# Generated by Django 4.2.27 on 2026-01-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0017_alter_note_last_activity_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_activity_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
