# Generated by Django 4.2.27 on 2026-01-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0017_kpi_start_value'),
        ('CPMS_app', '0018_alter_note_last_activity_at'),
    ]

    operations = [
    ]
