# Generated by Django 6.0 on 2026-01-23 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0026_progresslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPMS_app.department'),
        ),
    ]
