# Generated by Django 4.2.27 on 2026-01-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0028_alter_department_id_alter_initiative_id_alter_kpi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='initiative_status',
            field=models.CharField(choices=[('NS', 'لم يبدأ بعد'), ('IP', 'قيد التنفيذ'), ('D', 'متأخر'), ('C', 'مكتمل')], default='NS', max_length=2),
        ),
        migrations.AlterField(
            model_name='log',
            name='record_id',
            field=models.CharField(null=True),
        ),
    ]
