# Generated by Django 4.2.27 on 2026-01-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0029_initiative_initiative_status_alter_log_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='initiative_status',
        ),
    ]
