# Generated by Django 4.2.27 on 2026-01-31 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0030_remove_initiative_initiative_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiative',
            options={'ordering': ['-start_date'], 'verbose_name': 'Initiative', 'verbose_name_plural': 'Initiatives'},
        ),
        migrations.AlterModelOptions(
            name='strategicgoal',
            options={'ordering': ['-start_date'], 'verbose_name': 'StrategicGoal', 'verbose_name_plural': 'StrategicGoals'},
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 31)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 31)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 31)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 31)),
            preserve_default=False,
        ),
    ]
