# Generated by Django 4.2.27 on 2026-01-28 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0030_remove_initiative_initiative_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategicgoal',
            options={'ordering': ['-start_date'], 'verbose_name': 'StrategicGoal', 'verbose_name_plural': 'StrategicGoals'},
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='end_date',
            field=models.DateField(default=' ', help_text='تاريخ نهاية الهدف'),
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='تاريخ بداية الهدف'),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='end_date',
            field=models.DateField(default=' ', help_text='تاريخ نهاية الخطة'),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='تاريخ بداية الخطة'),
        ),
    ]
