# Generated by Django 4.2.27 on 2026-01-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0031_alter_strategicgoal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicgoal',
            name='end_date',
            field=models.DateField(default='YYYY-MM-DD', help_text='تاريخ نهاية الهدف'),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='end_date',
            field=models.DateField(default='YYYY-MM-DD', help_text='تاريخ نهاية الخطة'),
        ),
    ]
