# Generated by Django 4.2.27 on 2026-01-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0032_alter_strategicgoal_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicgoal',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='end_date',
            field=models.DateField(),
        ),
    ]
