# Generated by Django 4.2.27 on 2026-01-28 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0033_alter_strategicgoal_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicgoal',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='تاريخ نهاية الخطة'),
        ),
    ]
