# Generated by Django 4.2.27 on 2026-01-28 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMS_app', '0034_alter_strategicgoal_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicgoal',
            name='end_date',
            field=models.DateField(blank=True, help_text='تاريخ نهاية الهدف', null=True),
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='تاريخ بداية الهدف', null=True),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='end_date',
            field=models.DateField(blank=True, help_text='تاريخ نهاية الخطة', null=True),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='تاريخ بداية الخطة', null=True),
        ),
    ]
